services:
  - type: web
    name: youtube-sport-timer
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://easylive1989.github.io
    autoDeploy: true
